### ISSUE TITLE
global-stats

### ISSUE THREAD

**Issue by aaadriana** [fac22/Adriana_Elena-API#9]
render the global stats

**Comment by elenamarinaki** [comment]
I can do this if you haven't started yet :)

**Comment by aaadriana** [comment]
Yep, it's all yours😁

**Comment by elenamarinaki** [comment]
yay!!! 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 
🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 🤣 
I like it actually ;)

**Comment by aaadriana** [comment]
close #9
